### PR TITLE
Proofread of sec.virtguide.rtkvmguests

### PR DESCRIPTION
**Pull request by cjschroder**
There are some questions inline.
Corrections are mostly smoothing the wording, please review to make sure I didn't change the meaning or introduce errors.
@tomschr

### CODE REVIEW

**Comment by tomschr** [comment]
@cjschroder This is great! Thank you very much! I will clarify your remarks with Jeffrey.

**Comment by JeffreyCheung** [comment]
I am fine with the corrections made.  However, since the new section is for RT SP3, we need to put the new section after the section <sect1 xml:id="sec.virtguide.docker"> because this one is for RT SP2.

**Comment by tomschr** [comment]
> I am fine with the corrections made.

Great! 👍

>  However, since the new section is for RT SP3, we need to put the new section after the section because this one is for RT SP2.

I'm not sure I parsed your sentence correctly. 😉 Just to be sure: you mean, the new section  `sec.virtguide.rtkvmguests` should appear *at the end* of the Virtualization Guide, right?

**Comment by JeffreyCheung** [comment]
Yes, please.

**Comment by tomschr** [comment]
Ok, this is now done, see commit 3996d779.

**Pull request merged**
